name: CI
on: push

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Upgrade to at least corepack@0.31.0 to avoid
      # `Cannot find matching keyid` error
      # https://github.com/karlhorky/upleveled.io/pull/850#issuecomment-2646349719
      #
      # TODO: Remove when GitHub Actions runners have corepack@>=0.31.0
      - run: npm install -g corepack@>=0.31.0

      - run: corepack enable

      - run: |
          pnpm setup
          source /home/runner/.bashrc
        env:
          SHELL: bash

      # Uncomment to fix the issue
      # - run: echo "PNPM_HOME=/home/runner/.local/share/pnpm" >> "$GITHUB_ENV"
      # - run: echo "$PNPM_HOME" >> "$GITHUB_PATH"

      # Unset
      - run: echo $PNPM_HOME
      # Unset
      - run: pnpm bin --global

      # pnpm cannot find the global bin dir
      # ERR_PNPM_NO_GLOBAL_BIN_DIR
      - run: pnpm add --global @upleveled/preflight
